# Generated by Django 5.0.1 on 2024-03-05 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userincome", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={},
        ),
    ]
